openapi: 3.0.3
info:
  title: Recovery Kit
  description: |-
    The below describes the endpoints we will implement.
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: Derivation
    description: Everything about address derivation
    externalDocs:
      description: Find out more
      url: https://river.com/learn/terms/b/bip-44-derivation-paths-for-p2pkh/
  - name: Key Recovery
    description: Operations about key recovery
paths:
  /recover-keys:
    post:
      tags:
        - Key Recovery
      summary: Recover Extended Keys
      description: Retrieves XPRV, FPRV, XPUB, FPUB. Zip & RSA key should be in base 64 format.
      operationId: recoverKeys
      parameters:
        - name: recover-prv
          in: query
          description: Whether to recover the XPRV and FPRV as well as the XPUB and FPUB. If returned, will return partial info only.
          schema:
            type: boolean
            default: False
      requestBody:
        description: Zip & RSA key should be in base 64 format.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecoverKeysRequest'
        required: true

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecoverKeysResponse'
        '404':
          description: Test
        '405':
          description: Test

  /show-extended-private-keys:
    get:
      tags:
        - Key Recovery
      summary: Retrieve full extended keys to show
      description: Retrieves full info of XPRV, FPRV
      operationId: showFullPrv

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowExtendedKeyResponse'
        '404':
          description: Test
        '405':
          description: Test

  /derive-addresses:
    get:
      tags:
        - Derivation
      summary: Derives a certain amount of addresses
      description: Given an asset, vault and index (if UTXO), returns the private key, public key, and list of addresses & paths (or single address & path).
      operationId: deriveAddress
      parameters:
        - name: asset
          in: query
          required: true
          description: The symbol of the asset (BTC, ETH, SOL and so on).
          schema:
            type: string
            default:
        - name: account
          in: query
          required: true
          description: The vault ID.
          schema:
            type: integer
        - name: index_start
          in: query
          required: true
          description: The starting index of derivation.
          schema:
            type: integer
        - name: index_end
          in: query
          required: true
          description: The ending index of derivation.
          schema:
            type: integer
        - name: change
          in: query
          required: true
          description: The change according to BIP-44.
          schema:
            type: integer
            default: 0
        - name: xpub
          in: query
          required: true
          description: Derive addresses only from the xpub
          schema:
            type: boolean
            default: false
        - name: legacy
          in: query
          description: Get the legacy format of this asset if applies.
          schema:
            type: boolean
            default: false
        - name: checksum
          in: query
          description: Get the checksumed format of this asset if applies.
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeriveAddressesResponse'
        '404':
          description: Test
        '405':
          description: Test

  /show-private-key:
    get:
      tags:
        - Derivation
      summary: Retrieve private key to show
      description: Retrieves full info of PRV.
      operationId: showPrv
      parameters:
        - name: asset
          in: query
          description: The symbol of the asset (BTC, ETH, SOL and so on).
          schema:
            type: string
            default:
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowKeyResponse'
        '404':
          description: Test
        '405':
          description: Test

components:
  schemas:
    RecoverKeysRequest:
      properties:
        zip:
          type: string
        passphrase:
          type: string
        rsa-key:
          type: string
        rsa-key-passphrase:
          type: string
    RecoverKeysResponse:
      properties:
        xpub:
          type: string
        fpub:
          type: string
        xprv:
          type: string
        fprv:
          type: string
    ShowExtendedKeyResponse:
      properties:
        xprv:
          type: string
        fprv:
          type: string
    DeriveAddressesResponse:
      type: array
      items:
        type: object
        properties:
          prv:
            type: string
          pub:
            type: string
          address:
            type: string
          path:
              type: string
    ShowKeyResponse:
      properties:
        prv:
          type: string